export const R2_PUBLIC_DOMAIN_STORAGE_KEY = 'FLAQ-SAAS-TEMPLATE-r2-public-domain';
export const R2_ACCOUNT_ID_STORAGE_KEY = 'FLAQ-CREATOR-DESKTOP-r2-account-id';
export const R2_ACCESS_KEY_ID_STORAGE_KEY = 'FLAQ-CREATOR-DESKTOP-r2-access-key-id';
export const R2_SECRET_ACCESS_KEY_STORAGE_KEY = 'FLAQ-CREATOR-DESKTOP-r2-secret-access-key';
export const R2_BUCKET_NAME_STORAGE_KEY = 'FLAQ-CREATOR-DESKTOP-r2-bucket-name';

export const DESKTOP_R2_STORAGE_KEYS = [
  R2_ACCOUNT_ID_STORAGE_KEY,
  R2_ACCESS_KEY_ID_STORAGE_KEY,
  R2_SECRET_ACCESS_KEY_STORAGE_KEY,
  R2_BUCKET_NAME_STORAGE_KEY,
  R2_PUBLIC_DOMAIN_STORAGE_KEY,
];
